version: '3.8'

services:
  backend:
    build:
      context: ./FlowInvoice/FlowInvoice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-flowinvoice
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8080/api  
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend-flowinvoice:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
